// FILE GENERATED BY SCRIPT
// CHANGES TO THIS FILE WILL NOT
// BE KEPT AFTER COMPILATION

package lite;

import static lite.Expr.*;

abstract class ExprVisitor{
	interface Visitor<T> {
		T visitBinaryExpr(Binary expr);
		T visitTernaryExpr(Ternary expr);
		T visitAssignExpr(Assign expr);
		T visitUnaryExpr(Unary expr);
		T visitVariableExpr(Variable expr);
		T visitGroupingExpr(Grouping expr);
		T visitLiteralExpr(Literal expr);
	}
}
