// FILE GENERATED BY SCRIPT
// CHANGES TO THIS FILE WILL NOT
// BE KEPT AFTER COMPILATION

package lite;

import java.util.List;

abstract class Stmt{

	abstract <T> T accept(Visitor<T> visitor);

	interface Visitor<T> {
		T visitBlockStmt(Block stmt);
		T visitExpressionStmt(Expression stmt);
		T visitIfStmt(If stmt);
		T visitPrintStmt(Print stmt);
		T visitVarStmt(Var stmt);
		T visitWhileStmt(While stmt);
	}

	static class Block extends Stmt {
		Block(List<Stmt> statements){
			this.statements=statements;
		}
		final List<Stmt> statements;
		@Override
		<T> T accept(Visitor<T> visitor){
			return visitor.visitBlockStmt(this);
		}
	}
	static class Expression extends Stmt {
		Expression(Expr expression){
			this.expression=expression;
		}
		final Expr expression;
		@Override
		<T> T accept(Visitor<T> visitor){
			return visitor.visitExpressionStmt(this);
		}
	}
	static class If extends Stmt {
		If(Expr condition, Stmt thenBranch, Stmt elseBranch){
			this.condition=condition;
			this.thenBranch=thenBranch;
			this.elseBranch=elseBranch;
		}
		final Expr condition;
		final Stmt thenBranch;
		final Stmt elseBranch;
		@Override
		<T> T accept(Visitor<T> visitor){
			return visitor.visitIfStmt(this);
		}
	}
	static class Print extends Stmt {
		Print(Expr expression){
			this.expression=expression;
		}
		final Expr expression;
		@Override
		<T> T accept(Visitor<T> visitor){
			return visitor.visitPrintStmt(this);
		}
	}
	static class Var extends Stmt {
		Var(Token name, Expr initializer){
			this.name=name;
			this.initializer=initializer;
		}
		final Token name;
		final Expr initializer;
		@Override
		<T> T accept(Visitor<T> visitor){
			return visitor.visitVarStmt(this);
		}
	}
	static class While extends Stmt {
		While(Expr condition, Stmt body){
			this.condition=condition;
			this.body=body;
		}
		final Expr condition;
		final Stmt body;
		@Override
		<T> T accept(Visitor<T> visitor){
			return visitor.visitWhileStmt(this);
		}
	}
}
