// FILE GENERATED BY SCRIPT
// CHANGES TO THIS FILE WILL NOT
// BE KEPT AFTER COMPILATION

package lite;

import static lite.Stmt.*;

abstract class StmtVisitor{
	interface Visitor<T> {
		T visitBlockStmt(Block stmt);
		T visitExpressionStmt(Expression stmt);
		T visitIfStmt(If stmt);
		T visitPrintStmt(Print stmt);
		T visitVarStmt(Var stmt);
	}
}
