package lite;

enum TokenType{
    // Always one symbol
    LEFT_PAREN,RIGHT_PAREN,
    LEFT_BRACE,RIGHT_BRACE,
    COMMA,DOT,SEMICOLON,
    MINUS,PLUS,SLASH,STAR,
    BIT_OR,BIT_AND,BIT_XOR,
    BIT_NOT, QUESTION_MARK,
    COLON,

    // One or two symbols
    BANG,BANG_EQUAL,EQUAL,EQUAL_EQUAL,
    GREATER,GREATER_EQUAL,LESS,LESS_EQUAL,

    // Literals
    IDENTIFIER,STRING,NUMBER,

    // Keywords 
    AND,CLASS,ELSE,FALSE,FN,FOR,IF,NIL,OR,PRINT,
    RETURN,SUPER,THIS,TRUE,VAR,WHILE,

    EOF
}